#!/bin/bash

NTK_REPOSITORY="`echo ~/tmp/netsukuku`"

if [ ! -d $NTK_REPOSITORY ]
then
	echo Adjust the '$NTK_REPOSITORY' variable
	exit 1
fi
cd $NTK_REPOSITORY

rsync -auv -P --delete proto/2html freaknet.org:netsukuku/

rsync -auv -P ChangeLog doc/faq/FAQ README freaknet.org:netsukuku/files/
rsync -auv -P doc/main_doc/netsukuku doc/main_doc/netsukuku.ita doc/faq/FAQ freaknet.org:netsukuku/
rsync -auv -LP -C 'CVS' --exclude '*~' --delete  doc freaknet.org:netsukuku/files/

cd site/
rsync -auv -P contacts  home  index.php  logo_netsukuku.jpg  style.css freaknet.org:netsukuku/
cd ../
