=head1 NAME

netsukuku_d - Netsukuku protocol daemon

=head1 SYNOPSIS

netsukuku_d [-hvadrD46] [-i net_interface] [-c conf_file]

=head1 DESCRIPTION


Netsukuku is a mesh network or a P2P net system that generates and sustains
itself autonomously. It is designed to handle an unlimited number of nodes with
minimal CPU and memory resources. Thanks to this feature it can be easily
used to build a worldwide distributed, anonymous and anarchical network,
separated from the Internet, without the support of any servers, ISPs or
authority controls.
Keep in mind that it is a _physical network_, it isn't built upon any other
existing net, therefore there must be computers linked _physically_ each
other, then Netsukuku will build the routes.
For more information read the section "2.4  So, WTF is it?" of the
document.

In order to join to Netsukuku you have to use B<netsukuku_d>, which is the
daemon implenting the Npv7 protocol.
The daemon at startup takes the list of all the network interfaces which are
currently UP and it uses all of them to send and receive packets. If you want
to force the daemon to use specific interfaces you should use the B<-i>
option.
The ports it listens to are: 269-udp, 269-tcp, 271-udp, 277-udp, 277-tcp. So
be sure to open them in the firewall.


For more information about Netsukuku visit:
L<http://netsukuku.freaknet.org>

=head1 OPTIONS

=over

=item B<-4>, B<--ipv4> 

Forces the daemon to use ipv4 addresses only

=back

=over

=item B<-6>, B<--ipv6> 

Forces the daemon to use ipv6 addresses only. Warning, this is still
experimental.

=back

=over

=item B<-i> I<interface>, B<--iface> I<interface> 

Specifies the network interface the daemon will use to join Netsukuku, i.e.
wlan0. You can use more than one interface by specifying multiple times the
B<-i> option. For example: B<netsukuku_d> -i wlan0 -i eth0 -i wifi1 -i eth1

=back

=over

=item B<-a>, B<--no_andna> 

Forces B<netsukuku_d> to don't run the ANDNA daemon when started.

=back

=over

=item B<-R>, B<--no_resolv>

When B<NetsukukuD> starts it modifies F</etc/resolv.conf> writing in the first
line the string "nameserver 127.0.0.1". The old F</etc/resolv.conf> is copied in
F</etc/resolv.conf.bak>. When the daemon is closed F</etc/resolv.conf> is
restored. If you want to disable this set use the B<-R> option.

=back

=over

=item B<-r>, B<--restricted> 

With this option the daemon will run in restricted mode as specified in
the Npv7, only IPs of the private class will be choosen. It is used for
Internet compatibility.

=back

=over

=item B<-D>, B<--no_daemon> 

This option tells B<netsukuku_d> to don't detach to background and
daemonizing itself. The daemon will run on foreground instead.

=back

=over

=item B<-c> I<configuration_file>, B<--conf> I<configuration_file> 

Specifies the name of the configuration file. The
default is /etc/netsukuku/netsukuku.conf. B<netsukuku_d> will not start
without a configuration file.

=back

=over

=item B<-d>, B<--debug> 

With this option the daemon will run with displaying its debug messages.
The more -d you specify the more debug messages you'll get. Sometimes it's
cool to use it, but be careful and don't go insane ;)

=back

=over

=item B<-h>, B<--help> 

Display a the list of available options and their brief description.

=back

=over

=item B<-v>, B<--version> 

Displays the version of the B<netsukuku_d> daemon.

=back

=head1 EXAMPLES

Usually you'll just want to use B<netsukuku_d> with a wifi device:

netsukuku_wifi wlan0

netsukuku_d -i wlan0

If you one to use more than one network interface:

netsukuku_d -i eth0 -i wlan0 -i wifi1 -i eth2

=head1 SIGNALS

When the B<SIGHUP> signal is sent to B<netsukuku_d>, the F<andna_hostnames> file
will be reloaded and it will try to register all the new added hostnames.

When the B<SIGALRM> signal is sent to B<netsukuku_d>, the resolved hostnames
cache will be flushed.

=head1 LOGS

If B<netsukuku_d> is started as a daemon (without the B<-D> option), all the
logs are sent to syslog under the LOG_DAEMON category.

If the no-daemon option (B<-D>) is used, all the logs are printed to
F<stderr>.

=head1 FILES

=over

=item F</etc/netsukuku/netsukuku.conf>

It is the default path for the B<netsukuku_d> configuration file. It's
possible to choose another file with the B<-c> option.

=back

=over 

=item F</etc/netsukuku/andna_hostnames>

It is the file where the hostnames to be registerd in ANDNA are kept one per
line. It's location can be changed by modifying its option in the
F<netsukuku.conf> file.

=back

=over 

=item
F</usr/share/netsukuku/ext_map_file>

=item
F</usr/share/netsukuku/int_map_file>

=item
F</usr/share/netsukuku/bnode_map_file>

They are the Netsukuku maps saved by the daemon. Their locations can be
changed in F<netsukuku.conf>.

=back

=over

=item
F</usr/share/netsukuku/andna_cache>

=item
F</usr/share/netsukuku/lcl_cache>

=item
F</usr/share/netsukuku/rh_cache>

=item
F</usr/share/netsukuku/counter_cache>

They are the saved ANDNA caches.  Their locations can be 
changed in F<netsukuku.conf>.

=back

=head1 BUGS

{ Don't panic! }

If you encounter any bug, please report it to netsukuku@freaknet.org or
contacts any author explaining what the problem is and if possible a way to
reproduce it.

=head1 CONTACTS

Subcrive to the netsukuku mailing to get help, be updated on the latest news
and discuss on its development.

To subscribe to the list, send a message to:
   <netsukuku-subscribe@freaknet.org>
   
We live night and day in IRC, come to see us in:
#netsukuku 
on the FreeNode irc server (irc.freenode.org).

=head1 AUTHORS

Andrea Lo Pumo aka AlpT <alpt@freaknet.org>

=head1 SEE ALSO

For more information about Netsukuku visit:
L<http://netsukuku.freaknet.org>

netsukuku_wifi(8), andna(8), iproute2(8), route(8)
