=head1 NAME

netsukuku_d - Netsukuku protocol daemon

=head1 SYNOPSIS

netsukuku_d [-hvadrD46] [-i net_interface] [-c conf_file]

=head1 DESCRIPTION


Netsukuku is a pure net which exploits the chaos, it generates and sustains
itself autonomously, having the shape of a fractal.
The fusion of pure net with fractals and chaos is the characteristic which
allows to Netsukuku to be a diffused and distributed, not centralized,
anonymous, anarchical, not controlled and autonomous net.

In order to join to Netsukuku you have to use B<netsukuku_d>, which is the
daemon implenting the Npv7 protocol.

For more information about Netsukuku visit:
L<http://netsukuku.freaknet.org>

=head1 OPTIONS

=over

=item B<-4>, B<--ipv4> 

Forces the daemon to use ipv4 addresses only

=back

=over

=item B<-6>, B<--ipv6> 

Forces the daemon to use ipv6 addresses only. Warning, this is still
experimental.

=back

=over

=item B<-i> I<interface>, B<--iface> I<interface> 

Specifies the network interface the daemon will use to join Netsukuku, i.e.
wlan0.

=back

=over

=item B<-a>, B<--no_andna> 

Forces B<netsukuku_d> to don't run the ANDNA daemon when started.

=back

=over

=item B<-r>, B<--restricted> 

With this option the daemon will run in restricted mode as specified in
the Npv7, only IPs of the private class will be choosen. It is used for
Internet compatibility.

=back

=over

=item B<-D>, B<--no_daemon> 

This option tells B<netsukuku_d> to don't detach to background and
daemonizing itself. The daemon will run on foreground instead.

=back

=over

=item B<-c> I<configuration_file>, B<--conf> I<configuration_file> 

Specifies the name of the configuration file. The
default is /etc/netsukuku/netsukuku.conf. B<netsukuku_d> will not start
without a configuration file.

=back

=over

=item B<-d>, B<--debug> 

With this option the daemon will run with displaying its debug messages.
The more -d you specify the more debug messages you'll get. Sometimes it's
cool to use it, but be careful and don't go insane ;)

=back

=over

=item B<-h>, B<--help> 

Display a the list of available options and their brief description.

=back

=over

=item B<-v>, B<--version> 

Displays the version of the B<netsukuku_d> daemon.

=back

=head1 EXAMPLES

Usually you'll just want to use B<netsukuku_d> with a wifi device:

netsukuku_wifi wlan0

netsukuku_d -i wlan0

=head1 FILES

=over

=item F</etc/netsukuku/netsukuku.conf>

It is the default path for the B<netsukuku_d> configuration file. It's
possible to choose another file with the B<-c> option.

=back

=over 

=item F</etc/netsukuku/andna_hostnames>

It is the file where the hostnames to be registerd in ANDNA are kept one per
line. It's location can be changed by modifying its option in the
F<netsukuku.conf> file.

=back

=over 

=item
F</usr/share/netsukuku/ext_map_file>

=item
F</usr/share/netsukuku/int_map_file>

=item
F</usr/share/netsukuku/bnode_map_file>

They are the Netsukuku maps saved by the daemon. Their locations can be
changed in F<netsukuku.conf>.

=back

=over

=item
F</usr/share/netsukuku/andna_cache>

=item
F</usr/share/netsukuku/lcl_cache>

=item
F</usr/share/netsukuku/rh_cache>

=item
F</usr/share/netsukuku/counter_cache>

They are the saved ANDNA caches.  Their locations can be 
changed in F<netsukuku.conf>.

=back

=head1 BUGS

{ Don't panic! }

If you encounter any bug, please report it to netsukuku@freaknet.org or
contacts any author explaining what the problem is and if possible a way to
reproduce it.

=head1 CONTACTS

Subcrive to the netsukuku mailing to get help, be updated on the latest news
and discuss on its development.

To subscribe to the list, send a message to:
   <netsukuku-subscribe@freaknet.org>
   
We live night and day in IRC, come to see us in:
#netsukuku 
on the FreeNode irc server (irc.freenode.org).

=head1 AUTHORS

Andrea Lo Pumo aka AlpT <alpt@freaknet.org>

=head1 SEE ALSO

For more information about Netsukuku visit:
L<http://netsukuku.freaknet.org>

netsukuku_wifi(8), iproute2(8), route(8)
